# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TestDPAE-ActiveDirectory"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

log: core
logger: console

plugins:
  Auth::Extensible:
    realms:
      up-ad:
        provider: ActiveDirectory
        host: 123.45.67.89
        domain: example
        principal: com
        allowed_groups:
          - support
          - developers
